create table if not exists public.profiles (
  id text primary key,
  display_name text not null default 'Signup Links',
  bio text not null default '',
  avatar_url text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  profile_id text not null references public.profiles(id) on delete cascade,
  label text not null,
  url text not null,
  position integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.profiles (id, display_name, bio, avatar_url)
values ('admin', 'Signup Links', 'Add your first links from the admin dashboard.', '')
on conflict (id) do nothing;
